pipeline {
    agent any

    stages {
        stage('Setup Environment') {
            steps {
                sh 'echo "Seting up environment..."'
                sh 'pip install numpy==1.21.2'
                sh 'pip install pandas==1.3.3'
                sh 'pip install scikit-learn==1.3.2'
            }
        }
        stage('Download Data') {
            steps {
                sh 'python3 lab2_Jenkins_automatic/script/download_data.py'
            }
        }
        stage('Preprocess Data') {
            steps {
                sh 'python3 lab2_Jenkins_automatic/script/preprocess.py'
            }
        }
        stage('Train Model') {
            steps {
                sh 'python3 lab2_Jenkins_automatic/script/train_model.py'
            }
        }
        stage('Test Model') {
            steps {
                sh 'python3 lab2_Jenkins_automatic/script/test_model.py'
            }
        }
    }
    post {
        always {
            sh 'echo "Pipeline comleted"'
        }
    }
}
